### ISSUE TITLE
Gerenciamento do Projeto

### ISSUE THREAD

**Issue by luanagpinax** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t1-projeto-cultivo-de-plantas#25]

**Comment by joaoalmei** [comment]
Gerenciamento do Projeto

A equipe utiliza metodologias ágeis, tendo escolhido o Scrum como base para definição do processo de desenvolvimento.

A equipe está organizada da seguinte maneira:

●	Scrum Master: 

●	Product Owner: 
 
●	Equipe de Desenvolvimento

○
○
○

●	Equipe de Design

○
○
	
Para organização e distribuição das tarefas do projeto, a equipe está utilizando o GitHub Project.

●	Backlog: Recebe as tarefas a serem trabalhadas e representa o Product Backlog. Todas as atividades identificadas no decorrer do projeto também devem ser incorporadas a esta lista.
●	To Do: Esta lista representa o Sprint Backlog. Ou seja, o Sprint atual que estamos trabalhando.
●	Doing: Quando uma tarefa tiver sido iniciada, ela é movida para cá.
●	Done: nesta lista são colocadas as tarefas que passaram pelos testes e controle de qualidade e estão prontos para ser entregues ao usuário. Não há mais edições ou revisões necessárias, ele está agendado e pronto para a ação.

O quadro kanban do grupo desenvolvido na ferramenta de gerenciamento de projetos está disponível através da URL https://github.com/orgs/ICEI-PUC-Minas-PMV-ADS/projects/369 e é apresentado, no estado atual, na Figura "Tela do Kaban". 



![Image](https://user-images.githubusercontent.com/127165847/233672401-1e03850d-f4f0-4978-8b06-89933528134a.png)

Figura - Tela do Kaban
