### ISSUE TITLE
Tela: Contato & Login

### ISSUE THREAD

**Issue by luanagpinax** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t1-projeto-cultivo-de-plantas#27]

**Comment by taymilagres** [comment]
![Image](https://user-images.githubusercontent.com/127251265/233511211-9256508e-3f8a-4315-9de8-00b49c371816.png)



![Image](https://user-images.githubusercontent.com/127251265/233511230-6580e156-9952-4cff-9f9e-18165e0e8dec.png)
