### ISSUE TITLE
Tela 7 - Esqueci Minha Senha

### ISSUE THREAD

**Issue by luanagpinax** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t1-projeto-cultivo-de-plantas#44]

**Comment by joaoalmei** [comment]
![Image](https://user-images.githubusercontent.com/127165847/235281547-4c960b5e-5623-44e5-add0-67a5b268c5f2.png)

**Comment by joaoalmei** [comment]
Layout padrão do site (HTML e CSS) que será utilizado em todas as páginas com a definição de identidade visual, aspectos de responsividade e iconografia.
