### ISSUE TITLE
Funcionalidade 6

### ISSUE THREAD

**Issue by luanagpinax** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t1-projeto-cultivo-de-plantas#51]

**Comment by AndreeGS** [comment]
Desenvolvimento da página "Fórum-Salvos" utilizando html e css:

![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t1-projeto-cultivo-de-plantas/assets/116499898/88c43450-d40a-4c16-8ee0-4e94f653d67e)
