### ISSUE TITLE
Tela 11 - Fórum (Novo tópico)

### ISSUE THREAD

**Issue by luanagpinax** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t1-projeto-cultivo-de-plantas#81]
![Image](https://user-images.githubusercontent.com/107646150/235565185-58e965d2-3855-447d-a5c7-56ea2fe617e5.png)

**Comment by brunasantos-dev** [comment]
![Image](https://user-images.githubusercontent.com/107646150/235564852-802fb69a-87d6-440e-8078-c985fe94ab0d.png)
