### ISSUE TITLE
Tela 8 - Nova Senha

### ISSUE THREAD

**Issue by luanagpinax** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t1-projeto-cultivo-de-plantas#85]

**Comment by joaoalmei** [comment]
![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t1-projeto-cultivo-de-plantas/assets/127165847/aacd1171-b328-429e-ba6d-cdb0de198923)
